#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
env:
  REPOSITORY_URL: https://github.com/chongshengB/rt-n56u.git
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/rt-n56u
  TIME_ZONE: Asia/Shanghai
  TARGET_NAME: NEWIFI3
  FIRMWARE_VERSION: 20200821
  FIRMWARE_DATEPREFIX: $(date +"%Y%m%d")
  FIRMWARE_AUTHOR: chongshengB
  FIRMWARE_PATH: /opt/firmwares
  BUILD_OWNER: MAOMAOBOSHI
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: false
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "###########################"
        pwd
        #
        sudo mv Btools /opt/
        cd /opt/Btools
        echo "sudo ls -l"
        pwd
        sudo ls -l
        echo "###########################"
        #
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        mkdir -p /opt/images/
        #
        cd /opt/Btools/Setconfig/
        sh install_Setconfig.sh
        #
        cd /opt/Btools/build_toolchain
        sh install_build_toolchain.sh
        #  
    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify modifyName 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
